const paragraphs = [
"The Great Blue Hole is a large underwater sinkhole located off the coast of Belize in Central America. It is a part of the larger Belize Barrier Reef Reserve System, which is a UNESCO World Heritage Site.The Great Blue Hole is circular in shape, with a diameter of approximately 300 meters (984 feet) and a depth of around 124 meters (407 feet). The hole was formed during the last ice age, when sea levels were much lower and the area was a large cave system. As the sea levels rose, the cave system was flooded, leaving behind the deep sinkhole that we see today.The Great Blue Hole is known for its clear blue waters, which offer excellent visibility for divers. The waters of the sinkhole are home to a variety of marine life, including Caribbean reef sharks, nurse sharks, and giant groupers. Divers can also encounter rare species such as the Caribbean octopus and the midnight parrotfish. Diving in the Great Blue Hole is considered an advanced dive due to the depth and the strong currents that can be present. However, experienced divers can explore the depths of the hole and observe the unique geological formations and marine life that inhabit it.",
"The sea, or the ocean, is one of the most awe-inspiring natural wonders on our planet. It is a vast and powerful body of water that covers over 70% of the Earth's surface, containing an incredible diversity of marine life and supporting countless ecosystems.For centuries, the sea has been a source of inspiration for artists, poets, and writers, who have sought to capture its beauty and power in their works. The sea has been celebrated as a symbol of freedom, adventure, and the limitless possibilities of the natural world.The sea is also a vital resource for human beings, providing food, transportation, and recreation. Many coastal communities around the world rely on the sea for their livelihoods, with fishing and tourism being major industries. The sea also plays a key role in global transportation, with shipping being one of the most important modes of transporting goods around the world.Despite its importance, the sea is facing a number of challenges, including pollution, overfishing, and climate change. These challenges threaten the delicate balance of marine ecosystems and the creatures that depend on them. It is important that we take steps to protect the sea and the incredible diversity of life that it supports.",
"The Red Sea is a body of water that is located between Africa and Asia, and it is bordered by several countries including Egypt, Sudan, Eritrea, Yemen, Saudi Arabia, and Jordan. It is known for its unique and diverse marine life, particularly its vibrant coral reefs and abundance of tropical fish.The coral reefs of the Red Sea are some of the most colorful and diverse in the world, and they support a wide variety of marine creatures, including hundreds of species of fish, sea turtles, sharks, and other creatures. The reefs are particularly famous for their hard corals, which form intricate structures and come in a wide variety of shapes and colors.The Red Sea's unique geography and climate have contributed to the diversity of its marine life. The sea is relatively warm and has a high salt content, which provides ideal conditions for the growth of coral reefs. The sea is also relatively sheltered from strong ocean currents, which helps to maintain the health of the reefs and the creatures that depend on them.The Red Sea is a popular destination for snorkelers and scuba divers, who come to explore its colorful coral reefs and encounter its diverse marine life. The sea is home to a number of dive sites, ranging from shallow reefs suitable for beginners to deeper wrecks and caves for more experienced divers.",
"The sea has played a significant role in shaping human civilization for thousands of years, with maritime trade and transportation being key drivers of economic growth and cultural exchange. From the earliest seafaring civilizations of the Mediterranean and the Indian Ocean to the modern era of global trade and shipping, the sea has been a vital conduit of goods, people, and ideas.One of the earliest and most famous seafaring civilizations was that of the ancient Greeks, who relied on maritime trade and commerce to build a vast empire. The Greeks established colonies throughout the Mediterranean and Black Sea regions, and their ships were instrumental in transporting goods such as olive oil, wine, and textiles across long distances.In the Middle Ages, the Indian Ocean was a center of trade and cultural exchange, with merchants from Africa, Asia, and Europe conducting business in ports such as Aden, Muscat, and Zanzibar. This maritime trade network was crucial for the spread of Islam, which spread along the trade routes and influenced the cultures of many coastal regions.During the Age of Exploration in the 15th and 16th centuries, European powers such as Portugal, Spain, and England used the sea to expand their empires and establish new trade routes. They also used the sea to transport enslaved Africans to the New World, which had a profound impact on the history and culture of the Americas.",
"The Na Pali Coast is located on the north shore of the island of Kauai in Hawaii, and it is widely regarded as one of the most beautiful coastlines in the world. The coast stretches for 17 miles and is characterized by towering sea cliffs that rise up to 4,000 feet above the ocean. The coastline is also home to a number of pristine beaches and hidden coves that are accessible only by boat or on foot.The Na Pali Coast is renowned for its rugged beauty and dramatic scenery. The sea cliffs are made of volcanic rock and are deeply serrated, with narrow valleys and steep ridges that create a striking landscape. The coast is also home to a variety of sea life, including dolphins, sea turtles, and humpback whales, which can be seen swimming and breaching in the waters off the coast.One of the best ways to experience the Na Pali Coast is by taking a boat tour. Many companies offer guided tours that take visitors along the coast, allowing them to see the sea cliffs and hidden coves up close. Visitors can also kayak along the coast or hike along the Kalalau Trail, which offers stunning views of the coastline from above.In addition to its natural beauty, the Na Pali Coast is also steeped in history and culture. The coast was home to ancient Hawaiian settlements, and visitors can still see the ruins of stone walls and terraces that were once used for agriculture. The area is also sacred to the Hawaiian people, who believe that it is the home of the spirits of their ancestors." ,
"The Taj Mahal is a stunning example of Mughal architecture and is widely considered one of the world's most beautiful buildings. It is located in Agra, India, and was commissioned by the Mughal Emperor Shah Jahan in memory of his wife Mumtaz Mahal.Construction of the Taj Mahal began in 1632 and took more than 20 years to complete, with thousands of artisans and laborers working tirelessly to create the stunning structure. The Taj Mahal is made of white marble and features intricate designs and carvings, including intricate calligraphy and delicate floral patterns.One of the most stunning features of the Taj Mahal is its central dome, which rises to a height of 240 feet and is surrounded by four smaller domes. The building also features four minarets, each standing 131 feet tall, that are designed to lean slightly away from the main structure in case of an earthquake.In addition to its stunning architectural features, the Taj Mahal is also surrounded by lush gardens and water features that add to its overall beauty and serenity. Visitors to the Taj Mahal can explore the building and its grounds, learn about its rich history and cultural significance, and take in the breathtaking views of this architectural masterpiece.",
"The Pyramids of Giza are one of the most recognizable and awe-inspiring ancient structures in the world. Located on the outskirts of Cairo, Egypt, the pyramids were constructed more than 4,500 years ago during the Old Kingdom period of Ancient Egypt.The pyramids were built as tombs for pharaohs and their consorts, and were believed to be a symbol of the pharaoh's power and authority. The largest of the three pyramids at Giza, the Great Pyramid, is the largest pyramid in the world and stands over 450 feet tall.Despite being constructed thousands of years ago, the Pyramids of Giza remain remarkably well-preserved and continue to fascinate scholars and visitors alike. The precise methods used to construct these massive structures remain a mystery, but it is believed that the ancient Egyptians used sophisticated techniques and tools to cut and transport the massive stones used to build the pyramids.Visitors to the Pyramids of Giza can explore the interior of the pyramids, which contain intricate burial chambers and corridors, as well as a network of tunnels and shafts used to transport the pharaoh's body and burial goods. The surrounding area is also home to numerous other ancient structures, including the Sphinx and the Valley of the Kings.",
"The Caribbean Sea is a beautiful and diverse region that is located in the western part of the Atlantic Ocean. It is bordered by several countries and territories, including Mexico, Central America, South America, and many of the islands of the Caribbean. The sea is known for its warm, crystal-clear waters, pristine white sand beaches, and colorful marine life, making it a popular destination for tourists from all over the world.One of the main attractions of the Caribbean Sea is its beautiful beaches. Many of the islands in the region have picture-perfect beaches with soft white sand and crystal-clear water, making them perfect for swimming, sunbathing, and water sports like snorkeling and scuba diving. Some of the most popular beaches in the Caribbean include Seven Mile Beach in Jamaica, Eagle Beach in Aruba, and Grand Anse Beach in Grenada.The Caribbean Sea is also known for its vibrant culture and rich history. The region is home to a diverse mix of cultures, including indigenous peoples, African descendants, and Europeans. This has led to a unique blend of music, food, and art that is found nowhere else in the world. Visitors can experience this culture through local festivals, music performances, and traditional cuisine, which often includes fresh seafood, tropical fruits, and spicy flavors." ,
"The Norwegian Fjords are a breathtakingly beautiful natural wonder located in the western part of Norway. They are formed by the glaciers that once covered the area, which carved deep valleys into the landscape that were then filled with seawater. The result is a stunning landscape of towering cliffs, steep mountainsides, and deep blue waters that is unlike anywhere else on Earth.The fjords are home to an incredible diversity of wildlife, including seals, sea eagles, and whales. The waters are also filled with fish, making the fjords a popular destination for fishing enthusiasts. Visitors can take a boat tour through the fjords to experience their beauty up close, or hike along the many trails that wind through the surrounding mountains and forests.One of the most famous fjords in Norway is the Geirangerfjord, which is a UNESCO World Heritage site. It is known for its stunning waterfalls, including the Seven Sisters and the Suitor, which cascade down the cliffs and into the fjord below. Other popular fjords include the Hardangerfjord, which is the second longest fjord in Norway, and the Sognefjord, which is the longest and deepest fjord in Norway and the second longest in the world.",
"The South Pacific Ocean is one of the world's largest and most remote oceans, stretching from the coasts of Australia and New Zealand to the shores of South America. It is known for its crystal clear waters, pristine beaches, and coral reefs that are teeming with life.The South Pacific is home to a vast array of marine species, including colorful tropical fish, sharks, whales, dolphins, and sea turtles. Many of these species are unique to the region, making it a haven for biodiversity and a popular destination for snorkeling and scuba diving.One of the most famous natural wonders of the South Pacific is the Great Barrier Reef, located off the coast of Australia. It is the largest coral reef system in the world, stretching for over 1,400 miles and home to thousands of species of fish, coral, and other marine life.Other popular destinations in the South Pacific include Fiji, Tahiti, and Bora Bora, all of which offer visitors the chance to experience the region's stunning natural beauty and vibrant culture. These islands are known for their pristine beaches, turquoise lagoons, and overwater bungalows, making them the perfect destination for a romantic getaway or a relaxing vacation.",
"The city of Venice is a unique and beautiful world heritage site built on water. Situated in the northeastern region of Italy, Venice is known for its intricate network of canals, stunning architecture, and rich cultural history.The city was founded more than 1,500 years ago, and its unique location on a group of islands in the Venetian Lagoon has helped it to maintain its distinct character and charm. The city's most famous landmark is the stunning St. Mark's Basilica, which was built in the 11th century and is adorned with beautiful mosaics and intricate carvings.Visitors to Venice can explore the city's narrow streets and bridges, take a gondola ride through the canals, or visit the numerous museums and galleries that showcase the city's rich artistic heritage. Venice is also known for its delicious cuisine, with seafood and pasta dishes being among the most popular.Despite its popularity with tourists, Venice faces numerous challenges, including rising sea levels and the erosion of its historic buildings. Efforts are underway to protect the city's cultural heritage and ensure that future generations can continue to enjoy its unique beauty and charm.In recognition of its cultural and historical significance, the city of Venice was declared a UNESCO World Heritage Site in 1987. It remains one of the most popular tourist destinations in Italy and a beloved symbol of the country's rich cultural heritage.",
"The Palace of Versailles is an iconic French landmark and a testament to the grandeur of French monarchy. It was built in the 17th century as a hunting lodge for Louis XIII, but was later expanded and renovated by his son Louis XIV into a lavish palace. The palace features stunning architecture, intricate gardens, and opulent furnishings and decorations.The Hall of Mirrors is one of the most impressive rooms in the palace, with 17 mirrored arches reflecting the light from the windows and chandeliers, creating a stunning effect. The Palace also has several other impressive rooms, including the King's and Queen's apartments, the Chapel, and the Opera House.The Gardens of Versailles are equally impressive, with over 800 hectares of manicured lawns, fountains, and sculptures. The gardens were designed in the formal French style, with geometric patterns and carefully placed sculptures and fountains.Today, the Palace of Versailles is open to visitors, who can explore the palace and gardens and learn about its history and significance. It is one of the most popular tourist attractions in France and a must-visit destination for anyone interested in history, art, and architecture."];

const item  = document.getElementById("items");
const dataContainer = document.getElementById("data");

function shuffle(array){
    let currentIndex = array.length;
    let randomIndex;

    while(currentIndex != 0){
        randomIndex = Math.floor(Math.random() * currentIndex);
        currentIndex--;

        [array[currentIndex], array[randomIndex]] = [
            array[randomIndex], array[currentIndex]
        ];
    }
    return array;
}

function generate(){

    if(item.value == 0){
        alert("The value cannot be Zero!");
    }else if (item.value > paragraphs.length){
        const randomIndex = Math.floor(Math.random() * paragraphs.length);
        dataContainer.innerHTML = `${paragraphs[randomIndex]}`;
    }else{
        const shuffleParagraphs = paragraphs;
        shuffle(paragraphs);

        const selectedParagraphs = shuffleParagraphs.slice(0,item.value);
        const paragraphsHTML = selectedParagraphs.map(paragraphs => `<p>${paragraphs}</p>`).join("");
        dataContainer.innerHTML = paragraphsHTML;
    }

}